#
# vjudge synchronizer config
#

vjudge-link: https://vjudge.net/contest/584640

board-link: https://board.xcpcio.com/icpc/48th/online-qualification-2

contest-length-proportional-scaling: True

vjudge-wait-time: 3

board-wait-time: 2

loop-wait-time: 3

vjudge-account: 

vjudge-password: 